[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "echo 'Multi-service deployment'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# PostgreSQL Database Service
[[services]]
name = "postgres"
source = "image"
image = "postgres:15-alpine"

[services.variables]
POSTGRES_DB = "urbandrives"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "urbandrives"
PGDATA = "/var/lib/postgresql/data"

[services.volumes]
"/var/lib/postgresql/data" = "postgres-data"

[services.healthcheck]
command = ["pg_isready", "-U", "postgres", "-d", "urbandrives"]
interval = 5
timeout = 5
retries = 5

# Backend Service
[[services]]
name = "backend"
source = "dockerfile"
dockerfile = "./backend/Dockerfile"

[services.variables]
PORT = "3000"
DATABASE_URL = "${{postgres.DATABASE_URL}}"
NODE_ENV = "production"
BETTER_AUTH_SECRET = "${{BETTER_AUTH_SECRET}}"
BETTER_AUTH_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

[services.deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

# Frontend Service
[[services]]
name = "frontend"
source = "dockerfile"
dockerfile = "./frontend/Dockerfile"

[services.variables]
VITE_BACKEND_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"

[services.deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"